---
title: "Tongji thesis figures for Chapter 3: Results"
output: html_notebook
---

Load libraries and public variables
```{r, include = FALSE} 
# This chunk will be evaluated but the output is suppressed
rmarkdown::render("../../publicVariables/createPublicVariables.Rmd")
```

```{r}
# File that contains simulation output data in a HDF5 directory structure specified in "/publicVariables/createPublicVariables.Rmd"
simOutputH5 <- paste0("../../dataProcessing/simOutputH5Data/", experimentID, "_output.h5")

# A comprehensive table that contains all simulation input and calculated output metrics
allSimInputOutput <- read_feather("../allSimInputOutput.feather")

# This folder contains raw output files from the simulations. This is needed for calculate_para_sp_mcpsr()
rawSimOutFolder <- "/team/batch_SMOTNT/experiment1_output"

# Where figures are stored
figureBaseFolder <- "../thesisFigures/"
```


```{r}
allSimInputOutput %>%
  filter(paraCombo=="dc_1_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>% 
  select(MTT, geneLength_codon) %>% 
  mutate(riboTranslocationSpeed = geneLength_codon/MTT) %>% 
  pull(riboTranslocationSpeed) %>% 
  mean()

6.64 *3 
```


# figure 3.6.1
```{r fig.height=3, fig.width=8}

fig_a <- allSimInputOutput %>%
  filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF != "YER053C-A", ORF != "YGR169C-A", ORF != "YLR106C", ORF != "YCR024C-B") %>% 
  select(ORF, RMMDR, r, dc) %>%
  mutate(dc_fct=factor(dc, levels=c("1", "0.8", "0.6", "0.4", "0.2", "0"))) %>%
  ggplot(aes(x=dc_fct, y=RMMDR)) +
  geom_boxplot(outlier.size = 0.1) +
  theme_bw() +
  labs(x="CMD level",
       y="Relative mean mRNA \ndegradation rates") +
  theme(
    text = element_text(size = 13),
  )

fig_b <- allSimInputOutput %>%
  filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF != "YER053C-A", ORF != "YGR169C-A", ORF != "YLR106C", ORF != "YCR024C-B") %>% 
  select(ORF, RMMDR, r, dc) %>%
  ggplot(aes(x=r, y=RMMDR)) +
  geom_boxplot(outlier.size = 0.1) +
  theme_bw() +
  labs(x="Ribosome protection",
       y="Relative mean mRNA \ndegradation rates") +
  theme(
    text = element_text(size = 13),
  )


fig_a + fig_b + plot_annotation(tag_levels = "A")

ggsave(paste0(figureBaseFolder,"figure3.6.1.png"), dpi=200, height = 3, width = 8)

####################################
allSimInputOutput %>%
  filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF != "YER053C-A", ORF != "YGR169C-A", ORF != "YLR106C", ORF != "YCR024C-B") %>% 
  select(ORF, RMMDR, r, dc) %>%
  compare_means(., formula = RMMDR~dc, ref.group = "0")


allSimInputOutput %>%
  filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF != "YER053C-A", ORF != "YGR169C-A", ORF != "YLR106C", ORF != "YCR024C-B") %>% 
  select(ORF, RMMDR, r, dc) %>%
  compare_means(., formula = RMMDR~r, ref.group = "0")
```

# figure 3.6.2 correlation between RMMDR and 5 seq features for dc_1_r_0
```{r fig.height = 6, fig.width = 8}
allSimInputOutput%>%  
  filter(paraCombo == "dc_1_r_0", mRNADecRateNeymotin_sec != 0, ORF != "YER053C-A", ORF != "YLR106C") %>%
  select(ORF, RMMDR, iniProb_log10, mRNAabundance_log10, mRNADecRateNeymotin_sec_log10, CAI, geneLength_codon_log10, MTT, MMDP) %>%
  #filter(RMMDR>0.7) %>%  # filter out the 1 outlier
  `colnames<-`(paste0("",c("ORF", "RMMDR", "initiationProbability", "initialmRNALevel", "mRNADecayRate", "CAI", "geneLength", "meanTranslationTime","CMDproportion"))) %>%
  pivot_longer(names_to = "feature", values_to = "featureVals", !c(ORF, RMMDR)) %>%
  ggplot(aes(x = featureVals, y = RMMDR)) +
    geom_point(size = 0.5) +
    facet_wrap(~factor(feature, levels = c("CAI","geneLength","initialmRNALevel","initiationProbability","mRNADecayRate","meanTranslationTime","CMDproportion")), scales = "free", nrow = 2, strip.position = "bottom") +
    theme_bw() +
    geom_smooth(method = "lm") +
    stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.3, label.y.npc = 0.05, size = 3) +
    labs(x = "",
       y = "Relative mean mRNA degradation rates") +
    scale_y_log10() +
    theme(text = element_text(size = 13),
        strip.text = element_text(color = "black"),  # can't use element_blank() here because it gives error when p1+p2
        strip.background = element_blank(),  
        strip.placement = "outside"     #to put the strip labels below x-axis
)

ggsave(paste0(figureBaseFolder,"figure3.6.2.png"), dpi=200, height = 6, width = 8)

```

# figure 3.6.3 see how the correlation between RMMDR and the 5 seq features change over paraCombos
```{r fig.height = 6, fig.width = 8}
allSimInputOutput%>%  
    filter(mRNADecRateNeymotin_sec != 0, paraCombo!="mRNAconstant") %>%
    select(ORF, RMMDR, iniProb_log10, mRNAabundance_log10, mRNADecRateNeymotin_sec_log10, CAI, geneLength_codon_log10, MTT, MMDP, paraCombo, dc, r) %>%
    `colnames<-`(paste0("",c("ORF", "RMMDR", "initiationProbability", "initialmRNALevel", "mRNADecayRate", "CAI", "geneLength", "TranslationTime", "CMDproportion", "paraCombo", "dc", "r"))) %>% 
    pivot_longer(names_to = "seqFeature", values_to = "featureVals", cols = 3:9) %>% 
    group_by(paraCombo,seqFeature) %>% 
    summarise(corrCoeff = cor(RMMDR, featureVals)) %>% 
    left_join(dc.r.df, by = "paraCombo") %>% 
    mutate(dc_fct = factor(dc, levels=c("1", "0.8", "0.6", "0.4", "0.2", "0"))) %>%
    ungroup() %>% 
    ggplot(aes(x = dc_fct, y = corrCoeff, color = r)) +
    geom_point(size = 0.5) +
    geom_line(aes(group = r)) +
    facet_wrap(~factor(seqFeature, levels = c("CAI","geneLength","initialmRNALevel","initiationProbability","mRNADecayRate","TranslationTime","CMDproportion")), scales = "free", nrow = 3) +
    theme_bw() +
    theme(text = element_text(size = 13)) +    
    labs(x = "CMD levels", y = "Pearson's correlation coefficient", color = "Ribosome\nprotection") #corr. coeff. between relative mean mRNA decay rates and seq features

ggsave(paste0(figureBaseFolder,"figure3.6.3.png"), dpi=200, height = 6, width = 8)

```

```{r fig.height = 8, fig.width = 8}

##############################################################

allSimInputOutput %>%
    filter(paraCombo != "mRNAconstant", ORF != "YER053C-A", mRNADecRateNeymotin_sec != 0, RMMDR>0.7) %>%
    ggplot(aes(x = CAI, y = RMMDR)) +
    geom_point(size = 0.5) +
    facet_grid(dc~r, labeller = labeller(dc = c("1" = "100%", "0.8" = "80%", "0.6" = "60%", "0.4" = "40%", "0.2" = "20%", "0" = "CMD 0%"), r = c("0" = "Ribosome protection =  0", "0.1" = "0.1", "0.4" = "0.4", "1" = "1"), label_parsed)) +
    theme_bw() +
    theme(text = element_text(size = 13),
              legend.position = "none",
              plot.margin = margin(r = 0, unit = "pt"),
              panel.grid = element_blank()
      ) +
        labs(x = 'CAI',
             y = 'Relative mean mRNA decay rates') +
        geom_smooth(method = "lm") +
        stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.5, label.y.npc = 0.4, size = 4) +
        scale_y_log10()
##############################################################

allSimInputOutput %>%
    filter(paraCombo != "mRNAconstant", ORF != "YER053C-A", mRNADecRateNeymotin_sec != 0, RMMDR>0.7) %>%
    ggplot(aes(x = geneLength_codon, y = RMMDR)) +
    geom_point(size = 0.5) +
    facet_grid(dc~r, labeller = labeller(dc = c("1" = "100%", "0.8" = "80%", "0.6" = "60%", "0.4" = "40%", "0.2" = "20%", "0" = "CMD 0%"), r = c("0" = "Ribosome protection =  0", "0.1" = "0.1", "0.4" = "0.4", "1" = "1"), label_parsed)) +
    theme_bw() +
    theme(text = element_text(size = 13),
              legend.position = "none",
              plot.margin = margin(r = 0, unit = "pt"),
              panel.grid = element_blank()
      ) +
        labs(x = 'Gene length (codon)',
             y = 'Relative mean mRNA decay rates') +
        geom_smooth(method = "lm") +
        stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.05, label.y.npc = 0.3, size = 4) +
        scale_x_log10() +
        scale_y_log10()
##############################################################

allSimInputOutput %>%
    filter(paraCombo != "mRNAconstant", ORF != "YER053C-A", mRNADecRateNeymotin_sec != 0, RMMDR>0.7) %>%
    ggplot(aes(x = mRNAabundance, y = RMMDR)) +
    geom_point(size = 0.5) +
    facet_grid(dc~r, labeller = labeller(dc = c("1" = "100%", "0.8" = "80%", "0.6" = "60%", "0.4" = "40%", "0.2" = "20%", "0" = "CMD 0%"), r = c("0" = "Ribosome protection =  0", "0.1" = "0.1", "0.4" = "0.4", "1" = "1"), label_parsed)) +
    theme_bw() +
    theme(text = element_text(size = 13),
              legend.position = "none",
              plot.margin = margin(r = 0, unit = "pt"),
              panel.grid = element_blank()
      ) +
        labs(x = 'Initial mRNA abundances',
             y = 'Relative mean mRNA decay rates') +
        geom_smooth(method = "lm") +
        stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.5, label.y.npc = 0.3, size = 4) +
        scale_x_log10() +
        scale_y_log10()
##############################################################

allSimInputOutput %>%
    filter(paraCombo != "mRNAconstant", ORF != "YER053C-A", mRNADecRateNeymotin_sec != 0, RMMDR>0.7) %>%
    ggplot(aes(x = iniProb, y = RMMDR)) +
    geom_point(size = 0.5) +
    facet_grid(dc~r, labeller = labeller(dc = c("1" = "100%", "0.8" = "80%", "0.6" = "60%", "0.4" = "40%", "0.2" = "20%", "0" = "CMD 0%"), r = c("0" = "Ribosome protection =  0", "0.1" = "0.1", "0.4" = "0.4", "1" = "1"), label_parsed)) +
    theme_bw() +
    theme(text = element_text(size = 13),
              legend.position = "none",
              plot.margin = margin(r = 0, unit = "pt"),
              panel.grid = element_blank()
      ) +
        labs(x = 'Initiation probabilities',
             y = 'Relative mean mRNA decay rates') +
        geom_smooth(method = "lm") +
        stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.05, label.y.npc = 0.25, size = 4) +
        scale_x_log10() +
        scale_y_log10()
##############################################################

allSimInputOutput %>%
    filter(paraCombo != "mRNAconstant", ORF != "YER053C-A", mRNADecRateNeymotin_sec != 0, RMMDR>0.7) %>%
    ggplot(aes(x = mRNADecRateNeymotin_sec, y = RMMDR)) +
    geom_point(size = 0.5) +
    facet_grid(dc~r, labeller = labeller(dc = c("1" = "100%", "0.8" = "80%", "0.6" = "60%", "0.4" = "40%", "0.2" = "20%", "0" = "CMD 0%"), r = c("0" = "Ribosome protection =  0", "0.1" = "0.1", "0.4" = "0.4", "1" = "1"), label_parsed)) +
    theme_bw() +
    theme(text = element_text(size = 13),
              legend.position = "none",
              plot.margin = margin(r = 0, unit = "pt"),
              panel.grid = element_blank()
      ) +
        labs(x = 'mRNA decay rates'~(sec^-1),
             y = 'Relative mean mRNA decay rates') +
        geom_smooth(method = "lm") +
        stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.5, label.y.npc = 0.2, size = 4) +
        scale_x_log10() +
        scale_y_log10()


##############################################################

allSimInputOutput %>%
    filter(paraCombo != "mRNAconstant", ORF != "YER053C-A", mRNADecRateNeymotin_sec != 0, RMMDR>0.7) %>%
    ggplot(aes(x = MTT, y = RMMDR)) +
    geom_point(size = 0.5) +
    facet_grid(dc~r, labeller = labeller(dc = c("1" = "100%", "0.8" = "80%", "0.6" = "60%", "0.4" = "40%", "0.2" = "20%", "0" = "CMD 0%"), r = c("0" = "Ribosome protection =  0", "0.1" = "0.1", "0.4" = "0.4", "1" = "1"), label_parsed)) +
    theme_bw() +
    theme(text = element_text(size = 13),
              legend.position = "none",
              plot.margin = margin(r = 0, unit = "pt"),
              panel.grid = element_blank()
      ) +
        labs(x = 'Mean translation time (second)',
             y = 'Relative mean mRNA decay rates') +
        geom_smooth(method = "lm") +
        stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.2, label.y.npc = 0.2, size = 4) +
        scale_x_log10() +
        scale_y_log10()

##############################################################

allSimInputOutput %>%
    filter(paraCombo != "mRNAconstant", dc != "0", ORF != "YER053C-A", mRNADecRateNeymotin_sec != 0, RMMDR>0.7) %>%
    ggplot(aes(x = MMDP, y = RMMDR)) +
    geom_point(size = 0.5) +
    facet_grid(dc~r, labeller = labeller(dc = c("1" = "100%", "0.8" = "80%", "0.6" = "60%", "0.4" = "40%", "0.2" = "CMD 20%", "0" = "CMD 0%"), r = c("0" = "Ribosome protection =  0", "0.1" = "0.1", "0.4" = "0.4", "1" = "1"), label_parsed)) +
    theme_bw() +
    theme(text = element_text(size = 13),
              legend.position = "none",
              plot.margin = margin(r = 0, unit = "pt"),
              panel.grid = element_blank()
      ) +
        labs(x = 'Proportion of mRNA undergoing CMD',
             y = 'Relative mean mRNA decay rates') +
        geom_smooth(method = "lm") +
        stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.5, label.y.npc = 0.7, size = 4) +
        scale_y_log10()

```





