---
title: "Tongji thesis figures for Chapter 3: Results"
output: html_notebook
---

Load libraries and public variables
```{r, include = FALSE} 
# This chunk will be evaluated but the output is suppressed
rmarkdown::render("../../publicVariables/createPublicVariables.Rmd")
```

```{r}
# File that contains simulation output data in a HDF5 directory structure specified in "/publicVariables/createPublicVariables.Rmd"
simOutputH5 <- paste0("../../dataProcessing/simOutputH5Data/", experimentID, "_output.h5")

# A comprehensive table that contains all simulation input and calculated output metrics
allSimInputOutput <- read_feather("../allSimInputOutput.feather")

# This folder contains raw output files from the simulations. This is needed for calculate_para_sp_mcpsr()
rawSimOutFolder <- "/team/batch_SMOTNT/experiment1_output"

# Where figures are stored
figureBaseFolder <- "../thesisFigures/"
```



# figure 3.5.1 Mean bound ribosomes across different combinations of CMD levels and ribosome protection indices 
```{r fig.height=5, fig.width=7}
allSimInputOutput %>%
  filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A", MMBR > 1e-01) %>% 
  select(ORF, MMBR, r, dc) %>%
  mutate(dc_fct=factor(dc, levels=c("1", "0.8", "0.6", "0.4", "0.2", "0"))) %>%
  ggplot(aes(x=dc_fct, y=MMBR, fill=r)) +
  geom_boxplot(outlier.size = 0.1) +
  theme_bw() +
  labs(x="CMD level",
       y="Mean mRNA averaged bound ribosome") +
  #geom_hline(aes(yintercept=median(as.numeric(unlist(allSimInputOutput %>% filter(paraCombo=="dc_1_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A")%>%select(MTT))))), color="red", linetype="dashed") +
  scale_x_discrete(labels=c("1"="100%", "0.8"="80%", "0.6"="60%", "0.4"="40%", "0.2"="20%", "0"="0")) +
  scale_y_log10() +
  scale_fill_discrete(name = "Ribosome protection") +
  theme(
    text = element_text(size = 13),
    legend.position = "top",
    legend.justification = "left"
  )

ggsave(paste0(figureBaseFolder,"figure3.5.1.png"), dpi=200, height = 5, width = 7)


allSimInputOutput %>%
    filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>%
    select(ORF, MMBR, r, dc) %>% 
    split(.$r) %>%    # compare all the red bars together, then green bars together..
    map(function(x){
      compare_means(MMBR ~ dc, x, method = "anova")
    })

allSimInputOutput %>%
    filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>%
    select(ORF, MMBR, r, dc) %>% 
    split(.$dc) %>%    # compare all the green bars together, then red bars together..
    map(function(x){
      compare_means(MMBR ~ r, x, method = "anova")
    })

allSimInputOutput %>%
    filter(paraCombo=="dc_1_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>%
    pull(MMBR) %>% 
    mean(na.rm=TRUE)

allSimInputOutput %>%
    filter(paraCombo=="dc_1_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>%
    select(ORF,MMBR,geneLength_codon) %>% 
    mutate(longOrShort = ifelse(geneLength_codon>=512,"long","short")) %>% 
    group_by(longOrShort) %>% 
    summarise(MMBRmean = mean(MMBR))
```
# figure 3.5.2
```{r fig.height=5, fig.width=7}
allSimInputOutput%>%  
    filter(mRNADecRateNeymotin_sec != 0, paraCombo!="mRNAconstant") %>%
    filter(MRD > 1e-05) %>% 
    mutate(dc_fct=factor(dc, levels=c("1", "0.8", "0.6", "0.4", "0.2", "0"))) %>%
    ggplot(aes(x=dc_fct, y=MRD, fill=r)) +
    geom_boxplot(outlier.size = 0.1) +
    theme_bw() +
    labs(x="CMD level",
         y="Ribosome density (per codon)") +
    #geom_hline(aes(yintercept=median(as.numeric(unlist(allSimInputOutput %>% filter(paraCombo=="dc_1_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A")%>%select(MTT))))), color="red", linetype="dashed") +
    scale_x_discrete(labels=c("1"="100%", "0.8"="80%", "0.6"="60%", "0.4"="40%", "0.2"="20%", "0"="0")) +
    scale_y_log10() +
    scale_fill_discrete(name = "Ribosome protection") +
    theme(
      text = element_text(size = 13),
      legend.position = "top",
      legend.justification = "left"
    )

ggsave(paste0(figureBaseFolder,"figure3.5.2.png"), dpi=200, height = 5, width = 7)


allSimInputOutput %>%
    filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>%
    select(ORF, MRD, r, dc) %>% 
    split(.$r) %>%    # compare all the red bars together, then green bars together..
    map(function(x){
      compare_means(MRD ~ dc, x, method = "anova")
    })

allSimInputOutput %>%
    filter(paraCombo!="mRNAconstant", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>%
    select(ORF, MRD, r, dc) %>% 
    split(.$dc) %>%    # compare all the green bars together, then red bars together..
    map(function(x){
      compare_means(MRD ~ r, x, method = "anova")
    })

# per codon density is 0.006541304, per 15 codon density is 0.098
allSimInputOutput %>%
    filter(paraCombo=="dc_1_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>%
    pull(MRD) %>% 
    mean(na.rm=TRUE)
```




# figure 3.5.3 correlation between mean bound ribosome (MTBR) and 5 seq features for dc_1_r_0 
```{r fig.height = 6, fig.width = 8}
allSimInputOutput%>%  
  filter(paraCombo == "dc_1_r_0", mRNADecRateNeymotin_sec != 0, ORF != "YER053C-A") %>%
  select(ORF, MMBR, iniProb_log10, mRNAabundance_log10, mRNADecRateNeymotin_sec_log10, CAI, geneLength_codon_log10) %>%
  filter(MMBR > 1e-01) %>%  
  `colnames<-`(paste0("",c("ORF", "MMBR", "initiationProbability", "initialmRNALevel", "mRNADecayRate", "CAI", "geneLength"))) %>%
  pivot_longer(names_to = "feature", values_to = "featureVals", !c(ORF, MMBR)) %>%
  ggplot(aes(x = featureVals, y = MMBR)) +
    geom_point(size = 0.3) +
    facet_wrap(~feature, scales = "free", nrow = 2, strip.position = "bottom") +
    theme_bw() +
    geom_smooth(method = "lm") +
    stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.5, label.y.npc = 0.2, size = 4) +
    labs(x = "",
       y = "Mean mRNA-averaged number of bound ribosomes") +
    scale_y_log10() +
    theme(text = element_text(size = 13),
        strip.text = element_text(color = "black"),  # can't use element_blank() here because it gives error when p1+p2
        strip.background = element_blank(),  
        strip.placement = "outside"     #to put the strip labels below x-axis
)

ggsave(paste0(figureBaseFolder,"figure3.5.3.png"), dpi=200, height = 6, width = 8)

```
# figure 3.5.4
```{r fig.height = 6, fig.width = 8}
###################################### MMBR normalized by length, i.e. ribosome density
allSimInputOutput%>%  
  filter(paraCombo == "dc_1_r_0", mRNADecRateNeymotin_sec != 0, ORF != "YER053C-A", MMBR > 1e-01) %>%
  select(ORF, MRD, iniProb_log10, mRNAabundance_log10, mRNADecRateNeymotin_sec_log10, CAI, geneLength_codon_log10) %>%
  `colnames<-`(paste0("",c("ORF", "MRD", "initiationProbability", "initialmRNALevel", "mRNADecayRate", "CAI", "geneLength"))) %>%
  pivot_longer(names_to = "feature", values_to = "featureVals", !c(ORF, MRD)) %>%
  ggplot(aes(x = featureVals, y = MRD)) +
    geom_point(size = 0.3) +
    facet_wrap(~feature, scales = "free", nrow = 2, strip.position = "bottom") +
    theme_bw() +
    geom_smooth(method = "lm") +
    stat_cor(aes(label = paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.5, label.y.npc = 0.95, size = 4) +
    labs(x = "",
       y = "Mean ribosome density") +
    scale_y_log10() +
    theme(text = element_text(size = 13),
        strip.text = element_text(color = "black"),  # can't use element_blank() here because it gives error when p1+p2
        strip.background = element_blank(),  
        strip.placement = "outside"     #to put the strip labels below x-axis
)

ggsave(paste0(figureBaseFolder,"figure3.5.4.png"), dpi=200, height = 6, width = 8)

```
# 
```{r fig.height = 6, fig.width = 8}
allSimInputOutput%>%  
    filter(mRNADecRateNeymotin_sec != 0, paraCombo!="mRNAconstant") %>%
    select(ORF, MMBR, iniProb_log10, mRNAabundance_log10, mRNADecRateNeymotin_sec_log10, CAI, geneLength_codon_log10, MTT, MMDP, RMMDR, paraCombo, dc, r) %>%
    `colnames<-`(paste0("",c("ORF", "MMBR", "initiationProbability", "initialmRNALevel", "mRNADecayRate", "CAI", "geneLength", "TranslationTime", "CMDproportion", "relativemRNAdecayRate","paraCombo", "dc", "r"))) %>% 
    pivot_longer(names_to = "seqFeature", values_to = "featureVals", cols = 3:10) %>% 
    group_by(paraCombo,seqFeature) %>% 
    summarise(corrCoeff = cor(MMBR, featureVals)) %>% 
    left_join(dc.r.df, by = "paraCombo") %>% 
    mutate(dc_fct = factor(dc, levels=c("1", "0.8", "0.6", "0.4", "0.2", "0"))) %>%
    ungroup() %>% 
    ggplot(aes(x = dc_fct, y = corrCoeff, color = r)) +
    geom_point(size = 0.5) +
    geom_line(aes(group = r)) +
    facet_wrap(~factor(seqFeature, levels = c("CAI","geneLength","initialmRNALevel","initiationProbability","mRNADecayRate","TranslationTime","CMDproportion","relativemRNAdecayRate")), scales = "free", nrow = 3) +
    theme_bw() +
    theme(text = element_text(size = 13)) +    
    labs(x = "CMD levels", y = "Pearson's correlation coefficient", color = "Ribosome\nprotection") #corr. coeff. between relative mean mRNA decay rates and seq features

#ggsave(paste0(figureBaseFolder,"figure3.5.5.png"), dpi=200, height = 6, width = 8)

```

# 
```{r fig.height = 6, fig.width = 8}
allSimInputOutput%>%  
    filter(mRNADecRateNeymotin_sec != 0, paraCombo!="mRNAconstant") %>%
    select(ORF, MRD, iniProb_log10, mRNAabundance_log10, mRNADecRateNeymotin_sec_log10, CAI, geneLength_codon_log10, MTT, MMDP, RMMDR, MMBR, paraCombo, dc, r) %>%
    `colnames<-`(paste0("",c("ORF", "MRD", "initiationProbability", "initialmRNALevel", "mRNADecayRate", "CAI", "geneLength", "TranslationTime", "CMDproportion", "relativemRNAdecayRate", "totalBoundRibo","paraCombo", "dc", "r"))) %>% 
    pivot_longer(names_to = "seqFeature", values_to = "featureVals", cols = 3:11) %>% 
    group_by(paraCombo,seqFeature) %>% 
    summarise(corrCoeff = cor(MRD, featureVals)) %>% 
    left_join(dc.r.df, by = "paraCombo") %>% 
    mutate(dc_fct = factor(dc, levels=c("1", "0.8", "0.6", "0.4", "0.2", "0"))) %>%
    ungroup() %>% 
    ggplot(aes(x = dc_fct, y = corrCoeff, color = r)) +
    geom_point(size = 0.5) +
    geom_line(aes(group = r)) +
    facet_wrap(~factor(seqFeature, levels = c("CAI","geneLength","initialmRNALevel","initiationProbability","mRNADecayRate","TranslationTime","CMDproportion","relativemRNAdecayRate","totalBoundRibo")), scales = "free", nrow = 3) +
    theme_bw() +
    theme(text = element_text(size = 13)) +    
    labs(x = "CMD levels", y = "Pearson's correlation coefficient", color = "Ribosome\nprotection") #corr. coeff. between relative mean mRNA decay rates and seq features

#ggsave(paste0(figureBaseFolder,"figure3.5.6.png"), dpi=200, height = 6, width = 8)
```

