---
title: "R Notebook"
output: html_notebook
---

Load libraries and public variables
```{r, include = FALSE} 
# This chunk will be evaluated but the output is suppressed
rmarkdown::render("../../publicVariables/createPublicVariables.Rmd")
```

```{r}
# File that contains simulation output data in a HDF5 directory structure specified in "/publicVariables/createPublicVariables.Rmd"
simOutputH5 <- paste0("../../dataProcessing/simOutputH5Data/", experimentID, "_output.h5")

# A comprehensive table that contains all simulation input and calculated output metrics
allSimInputOutput <- read_feather("../allSimInputOutput.feather")

# This folder contains raw output files from the simulations. This is needed for calculate_para_sp_mcpsr()
rawSimOutFolder <- "/team/batch_SMOTNT/experiment1_output"

# Where figures are stored
figureBaseFolder <- "../figures/"
```



```{r}
figure3a <- allSimInputOutput %>%
    filter(paraCombo == "dc_1_r_0", mRNADecRateNeymotin_sec != 0, mRNAabundance>1, ORF!="YER053C-A", ORF!="YLR106C") %>%  #remove the gene with HL=450min, also an outlier gene "YLR106C" with RMTE==0.6
    select(ORF, paraCombo, RMTE, mRNAabundance_log10, iniProb_log10, mRNADecRateNeymotin_sec_log10, CAI, geneLength_codon_log10) %>%
    `colnames<-`(c("ORF", "paraCombo", "RMTE", "log(mRNAabundance)", "log(IniProb)", "log(DecRate)", "CAI", "log(Length)")) %>%
    pivot_longer(cols = -c(RMTE, paraCombo, ORF), names_to = "feature", values_to = "featureVal") %>%
    ggplot(aes(x=featureVal, y=RMTE, color=paraCombo)) +
    geom_point(size=0.5) +
    facet_wrap(~feature, scales = "free", nrow=1, strip.position = "bottom") +
    theme_bw() +
    scale_y_log10() +
    theme(text = element_text(size = 13),
              legend.position = "none",
              strip.text = element_text(color="black", size=rel(1.2)),  # can't use element_blank() here because it gives error when p1+p2
              plot.margin = margin(r = 0, unit = "pt"),
              panel.grid = element_blank(),
              strip.background = element_blank(),  
              strip.placement = "outside"     #to put the strip labels below x-axis
      ) +
        labs(x = "",
             y = "Relative mean translation efficiency") +
        geom_smooth(method="lm") +
        stat_cor(aes(label=paste(..r.label..,  sep = "~`,`~")), label.x.npc = 0.3, label.y.npc = 0.2, size=5) +
        scale_color_manual(name="", labels=c(""), values = c("dc_1_r_0" = "#1F78B4"))



#################################################################
transEffiSeq <- allSimInputOutput %>% 
    filter(paraCombo == "dc_1_r_0", mRNADecRateNeymotin_sec != 0, mRNAabundance>1, ORF!="YER053C-A", ORF!="YLR106C") %>%
    select(RMTE, paraCombo, geneLength_codon_log10, iniProb_log10, CAI, mRNADecRateNeymotin_sec_log10, mRNAabundance_log10)

transEffiSeq$mRNADecRateNeymotin_sec_log10[which(is.infinite(transEffiSeq$mRNADecRateNeymotin_sec_log10))] <- NA #convert all with -Inf to NAs

corr_RMTE_seqFeature <- data.frame(cbind(round(do.call(rbind, lapply(3:7, function(x){(cor.test(transEffiSeq$RMTE, as.numeric(unlist(transEffiSeq[, x]))))$estimate})), 3),   # r= correlation coefficient
  do.call(rbind, lapply(3:7, function(x){(cor.test(transEffiSeq$RMTE, as.numeric(unlist(transEffiSeq[, x]))))$p.value})))) # pvalue for corr()

colnames(corr_RMTE_seqFeature) <- c("CorrCoef", "pval")
corr_RMTE_seqFeature$paraCombo <- rep("dc_1_r_0", 5)
corr_RMTE_seqFeature$feature <- c("log(geneLength)", "log(iniProb)", "CAI", "log(DecRate)", "log(mRNAabundance)")
corr_RMTE_seqFeature$feature[4] <- "log(DecRate)"


figure3b <- corr_RMTE_seqFeature %>%
  ggplot(aes(x=feature, 
             y=CorrCoef, fill=paraCombo)) +
    geom_bar(stat = "identity") + 
    ylim(-0.81, 0.81) +
    theme_bw() +
    scale_fill_manual(name="", labels=c("Co-trans 100% RiboProtect 0"), values = c("dc_1_r_0" = "#1F78B4")) +
    labs(x = "",
      y="Correlation coefficient for mean of \nrelative translation efficiencies") +
    theme(
      text = element_text(size = 13),
      legend.position="none",
      legend.justification = "left",
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.title.y = element_text(size = rel(1.4)),
      axis.text.x = element_text(size = rel(1.4)),
      axis.text.y = element_text(size = rel(1.4)),
      axis.ticks.y = element_blank()
    ) +
    scale_x_discrete(position = "top") +
    coord_flip() 

  
```



```{r fig.height = 5, fig.width=15}
figure3 <- (figure3a + figure3b + plot_layout(ncol = 2, width = c(3.8, 0.8)))
figure3 + 
  plot_annotation(
    title = "Figure 3",
    tag_levels = 'A') 

ggsave(paste0(figureBaseFolder,"c_fig_3.png"), dpi=200, height = 5, width = 15)


```
