---
title: "R Notebook"
output: html_notebook
---

Load libraries and public variables
```{r, include = FALSE} 
# This chunk will be evaluated but the output is suppressed
rmarkdown::render("../../publicVariables/createPublicVariables.Rmd")
```


```{r}
# File that contains simulation output data in a HDF5 directory structure specified in "/publicVariables/createPublicVariables.Rmd"
simOutputH5 <- paste0("../../dataProcessing/simOutputH5Data/", experimentID, "_output.h5")

# A comprehensive table that contains all simulation input and calculated output metrics
allSimInputOutput <- read_feather("../allSimInputOutput.feather")

# This folder contains raw output files from the simulations. This is needed for calculate_para_sp_mcpsr()
rawSimOutFolder <- "/team/batch_SMOTNT/experiment1_output"

# Where figures are stored
figureBaseFolder <- "../figures/"
```

```{r}
# Read in the files that conatins "AllgeneAlldcr.feather"
files.locs <- dir("../calculatedMetrics", pattern = "AllgeneAlldcr.feather", full.names = TRUE)
# read_feather for all the files in this location
calculatedMetrics.list <- sapply(files.locs, read_feather, simplify = FALSE)  
# exclude the path and only extract the data frame names, e.g. "mmcAllgeneAlldcr"
names(calculatedMetrics.list) <- str_sub(names(calculatedMetrics.list), nchar("../calculatedMetrics/")+1, -9)  

colnames(calculatedMetrics.list$mmmdAllgeneAlldcr) <- dc.r.df$paraCombo
colnames(calculatedMetrics.list$mmcAllgeneAlldcr) <- dc.r.df$paraCombo

# These numbers are the global ratio of mRNAs marked for decay (averaged by time and tech reps): global mRNAs marked for decay/total cellular mRNAs for each parameter combos
sum(calculatedMetrics.list$mmmdAllgeneAlldcr[, "dc_1_r_0"])/sum(calculatedMetrics.list$mmcAllgeneAlldcr[, "dc_1_r_0"])       #0.02440254
sum(calculatedMetrics.list$mmmdAllgeneAlldcr[, "dc_0.8_r_0"])/sum(calculatedMetrics.list$mmcAllgeneAlldcr[, "dc_0.8_r_0"])   #0.01972776
sum(calculatedMetrics.list$mmmdAllgeneAlldcr[, "dc_0.6_r_0"])/sum(calculatedMetrics.list$mmcAllgeneAlldcr[, "dc_0.6_r_0"])   #0.01498103
sum(calculatedMetrics.list$mmmdAllgeneAlldcr[, "dc_0.4_r_0"])/sum(calculatedMetrics.list$mmcAllgeneAlldcr[, "dc_0.4_r_0"])   #0.01010858
sum(calculatedMetrics.list$mmmdAllgeneAlldcr[, "dc_0.2_r_0"])/sum(calculatedMetrics.list$mmcAllgeneAlldcr[, "dc_0.2_r_0"])   #0.005121193

mean((allSimInputOutput%>% filter(paraCombo=="dc_1_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A"))$MMDP)     #0.04619035
mean((allSimInputOutput%>% filter(paraCombo=="dc_0.8_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A"))$MMDP)   #0.0374734
mean((allSimInputOutput%>% filter(paraCombo=="dc_0.6_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A"))$MMDP)   #0.02853558
mean((allSimInputOutput%>% filter(paraCombo=="dc_0.4_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A"))$MMDP)   #0.01931238
mean((allSimInputOutput%>% filter(paraCombo=="dc_0.2_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A"))$MMDP)   #0.009807305


figure4a <- allSimInputOutput %>%
    filter(paraCombo=="dc_1_r_0"|paraCombo=="dc_0.8_r_0"|paraCombo=="dc_0.6_r_0"|paraCombo=="dc_0.4_r_0"|paraCombo=="dc_0.2_r_0", mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A") %>% 
    mutate(MMDP_alt = ifelse(MMDP>1e-03, MMDP, 1e-03)) %>%
    ggplot(aes(x=MMDP_alt, fill=paraCombo)) +   
    geom_density(alpha=0.5) +
    labs(x = "Propotion of mRNA undergoing CMD for all genes", 
         title = "") +
    theme_bw() +
    scale_x_log10(labels = scales::percent) +
    theme(text = element_text(size = 13), 
        legend.position = c(0.14, 0.8), 
        legend.background = element_rect(fill=alpha(0.7)),
        legend.text = element_text(size=rel(0.7)),
        panel.grid = element_blank()
    ) +
    scale_fill_brewer(name = "", labels=c("dc_1_r_0"="100% CMD: 2.4%",
                                          "dc_0.8_r_0"="80% CMD: 2.0%",
                                          "dc_0.6_r_0"="60% CMD: 1.5%",
                                          "dc_0.4_r_0"="40% CMD: 1.0%",
                                          "dc_0.2_r_0"="20% CMD: 0.5%")) 

# cpsrAlldecAllrep contains the cpsr for all 50 tech reps of each paraCombo, it was not joined in allSimInputOutput
cpsrAlldcrAllrep <- read_feather("../calculatedMetrics/cpsrAlldcrAllrep.feather")
figure4b <- cpsrAlldcrAllrep %>%  
    pivot_longer(cols = everything(), names_to = "paraCombo", values_to = "CPSRval") %>%
    left_join(dc.r.df,  by="paraCombo") %>%
    filter(r==0) %>%
    mutate(norm.cpsr = CPSRval/median(cpsrAlldcrAllrep$dc_1_r_0)) %>%   # normalizing all cells against the median cpsr value of dc_1_r_0
    mutate(CoTransProportion = paste0(as.numeric(dc)*100, "%")) %>%
    ggplot(aes(x=CoTransProportion, y=norm.cpsr)) +
    geom_boxplot() +
    theme_bw() +
    labs ( title = "",
                x ="CMD levels",
                y = "Cellular protein synthesis rate\n(relative to the meadian of 100% CMD)") +
    theme(text = element_text(size = 13),
          panel.grid = element_blank()) +
    scale_x_discrete(limits = c("100%", "80%", "60%", "40%", "20%", "0%"))


figure4c <- (allSimInputOutput %>%
    filter(r==0, mRNADecRateNeymotin_sec!=0, ORF!="YER053C-A"))[, c("ORF", "RMPSR", "dc")] %>%
    spread(key=dc, value = RMPSR, sep="_") %>%
    mutate_at(vars(-ORF), funs(./dc_1)) %>%  # get all relative values to r_0
    `colnames<-`(c("ORF", "0", "20%", "40%", "60%", "80%", "100%")) %>%
    pivot_longer(-ORF, names_to = "CoTransProportion", values_to = "relMPSR") %>%
    ggplot(aes(x=CoTransProportion, y=relMPSR)) +
        geom_line(alpha=0.2, color="grey", aes(group = ORF)) +
        geom_hline(aes(yintercept=1), color="red", linetype="dashed") +
        theme_bw() +
        theme(
          text = element_text(size = 13),
          panel.grid = element_blank()
          ) +
        geom_violin(width = 0.8) +
        scale_x_discrete(limits = c("100%", "80%", "60%", "40%", "20%", "0")) +
        labs(x="CMD levels",
             y="Relative mean protein synthesis rate\n(relative to 100%)")
```

```{r fig.height = 9, fig.width=12.5}
figure4 <- (figure4a+figure4b)/figure4c
figure4 + 
  plot_annotation(
    title = "Figure 4",
    tag_levels = 'A') 

ggsave(paste0(figureBaseFolder, "d_fig_4.png"), dpi=200, height = 9, width = 12.5)

```

